/**
 * five9-elevenlabs-bridge / server.js
 *
 * Bridges Five9 VoiceStream (gRPC) → ElevenLabs real-time STT (WebSocket).
 *
 * Per-call flow:
 *   1. Five9 opens TWO separate gRPC sessions per call — one for the agent
 *      leg, one for the customer leg.  Both share the same vcc_call_id.
 *   2. Trust token is verified from gRPC metadata (x-five9-trust-token).
 *   3. For each gRPC session we open ONE ElevenLabs WebSocket.
 *   4. Each StreamMedia audio chunk (LINEAR16 @ 8 kHz) is forwarded as a
 *      base64-encoded `input_audio_chunk` to ElevenLabs.
 *   5. ElevenLabs returns partial/committed transcripts which are logged.
 *   6. StreamStop triggers cleanup.
 *
 * PROTO DISCOVERY MODE (PROTO_DISCOVERY=true):
 *   If the official Five9 proto differs from our placeholder, set
 *   PROTO_DISCOVERY=true.  The server will accept any gRPC call and dump the
 *   raw JSON of every incoming message so you can read the actual field names
 *   and update the proto to match.
 *
 * HTTP endpoints for Five9 callbacks:
 *   GET  /call-events                     — Subscription validation (SHA-256 challenge)
 *   POST /call-events                     — CTI Call events
 *   POST /subscriptions/:subscriptionId   — Stream Status events
 *   GET  /health                          — Health + active session count
 */

'use strict';

require('dotenv').config();

const path   = require('path');
const fs     = require('fs');
const crypto = require('crypto');
const grpc   = require('@grpc/grpc-js');
const loader = require('@grpc/proto-loader');
const WebSocket = require('ws');
const express   = require('express');

// ─── Config ──────────────────────────────────────────────────────────────────

const {
  ELEVENLABS_API_KEY,
  ELEVENLABS_MODEL_ID = 'scribe_v2_realtime',
  FIVE9_TRUST_TOKEN,
  FIVE9_API_KEY,           // Generated by Five9 at subscription creation (shown once).
                           // Used to authenticate CTI Call Event webhook POSTs via X-F9-APIKEY header.
  GRPC_PORT      = '50051',
  HTTP_PORT      = '3000',
  GRPC_TLS       = 'false',
  TLS_CERT_PATH,
  TLS_KEY_PATH,
  PROTO_DISCOVERY = 'false',
} = process.env;

if (!FIVE9_TRUST_TOKEN) throw new Error('Missing FIVE9_TRUST_TOKEN in environment');
if (PROTO_DISCOVERY !== 'true' && !ELEVENLABS_API_KEY) {
  throw new Error('Missing ELEVENLABS_API_KEY in environment');
}

const DISCOVERY_MODE = PROTO_DISCOVERY === 'true';
if (DISCOVERY_MODE) {
  console.log('⚠️  PROTO DISCOVERY MODE — raw gRPC messages will be logged. Do NOT use in production.');
}

// SHA-256 of trust token — returned during Five9 subscription validation (GET /call-events)
const TRUST_TOKEN_SHA256 = crypto.createHash('sha256').update(FIVE9_TRUST_TOKEN).digest('hex');

// ─── Proto loading ────────────────────────────────────────────────────────────

const PROTO_PATH = path.join(__dirname, 'five9_voice_stream.proto');

const packageDefinition = loader.loadSync(PROTO_PATH, {
  keepCase: true,       // preserve exact field names from Five9
  longs: String,
  enums: String,
  defaults: true,
  oneofs: true,
});

const { five9: { voicestream: proto } } = grpc.loadPackageDefinition(packageDefinition);

// ─── Active sessions ─────────────────────────────────────────────────────────
//
// Five9 opens ONE gRPC session per call leg (agent | customer).
// We track by  `${vccCallId}:${callLeg}`  so we can correlate transcripts.
// For health reporting we also count unique calls by vccCallId.

const sessions = new Map();   // key: `${callId}:${leg}` → { ws, callId, leg }

// ─── ElevenLabs WebSocket factory ────────────────────────────────────────────

function openElevenLabsSocket({ callId, leg, onTranscript }) {
  const url = new URL('wss://api.elevenlabs.io/v1/speech-to-text/realtime');
  url.searchParams.set('model_id',     ELEVENLABS_MODEL_ID);
  // Five9 gRPC sends LINEAR16 (signed 16-bit PCM) @ 8 kHz
  url.searchParams.set('audio_format', 'pcm_8000');

  const ws = new WebSocket(url.toString(), {
    headers: { 'xi-api-key': ELEVENLABS_API_KEY },
  });

  ws.on('open', () => console.log(`[EL][${callId}][${leg}] connected`));

  ws.on('message', (raw) => {
    let msg;
    try { msg = JSON.parse(raw.toString()); } catch { return; }

    switch (msg.type) {
      case 'session_started':
        console.log(`[EL][${callId}][${leg}] session_started`);
        break;
      case 'partial_transcript':
        if (msg.text) {
          console.log(`[EL][${callId}][${leg}] PARTIAL: ${msg.text}`);
          onTranscript({ callId, leg, type: 'partial', text: msg.text });
        }
        break;
      case 'committed_transcript':
        if (msg.text) {
          console.log(`[EL][${callId}][${leg}] FINAL:   ${msg.text}`);
          onTranscript({ callId, leg, type: 'final', text: msg.text });
        }
        break;
      default:
        if (msg.error || String(msg.type).includes('error')) {
          console.error(`[EL][${callId}][${leg}] error:`, msg);
        }
    }
  });

  ws.on('error', (err) => console.error(`[EL][${callId}][${leg}] WS error:`, err.message));
  ws.on('close', (code) => console.log(`[EL][${callId}][${leg}] closed (${code})`));

  return ws;
}

function sendAudioChunk(ws, audioBytes) {
  if (!ws || ws.readyState !== WebSocket.OPEN) return;
  ws.send(JSON.stringify({
    type:        'input_audio_chunk',
    audio_chunk: Buffer.from(audioBytes).toString('base64'),
  }));
}

// ─── Transcript handler — extend this ────────────────────────────────────────

function handleTranscript({ callId, leg, type, text }) {
  // TODO: write to DB, POST to CRM/webhook, push to agent UI via Socket.IO, etc.
  // leg is "agent" or "customer" (or "supervisor")
}

// ─── Trust token verification (from gRPC metadata, not proto body) ────────────

function verifyTrustToken(metadata) {
  // Five9 sends the trust token as a gRPC metadata header: x-five9-trust-token
  const values = metadata.get('x-five9-trust-token');
  if (!values || values.length === 0) {
    console.warn('[GR] Missing x-five9-trust-token header');
    return false;
  }
  if (values[0] !== FIVE9_TRUST_TOKEN) {
    console.warn('[GR] Invalid trust token received');
    return false;
  }
  return true;
}

// Read the call ID from gRPC metadata header (available before first data message)
function extractCallIdFromMetadata(metadata) {
  const values = metadata.get('x-five9-call-id');
  return (values && values.length > 0) ? values[0] : null;
}

// ─── Proto discovery helper ───────────────────────────────────────────────────

function logDiscovery(label, obj) {
  const cleaned = JSON.parse(JSON.stringify(obj, (k, v) => {
    if (k === 'payload' && Buffer.isBuffer(v)) return `<Buffer ${v.length} bytes>`;
    if (typeof v === 'string' && v.length > 200) return `<string ${v.length} chars>`;
    return v;
  }));
  console.log(`\n📦 [DISCOVERY] ${label}:\n`, JSON.stringify(cleaned, null, 2), '\n');
}

// ─── gRPC service implementation ──────────────────────────────────────────────
//
// Five9 opens ONE gRPC session per call leg.  We open ONE ElevenLabs WebSocket
// per gRPC session.  callLeg ("agent" | "customer") comes from StreamStart.

function startStream(call) {
  let callId  = extractCallIdFromMetadata(call.metadata);  // early from header
  let leg     = null;   // "agent" | "customer"
  let ws      = null;   // ElevenLabs WebSocket for this leg
  let sessionKey = null;

  // ── Verify trust token from metadata on connection ─────────────────────────
  if (!verifyTrustToken(call.metadata)) {
    console.warn('[GR] Rejected — bad/missing trust token');
    call.destroy(new Error('Unauthorized'));
    return;
  }

  call.on('data', (request) => {

    // ── DISCOVERY MODE: dump every raw message ─────────────────────────────
    if (DISCOVERY_MODE) {
      logDiscovery('incoming message', request);
      call.write({ call_id: callId || 'unknown', status: 'OK', message: 'discovery-ack' });
      return;
    }

    const eventType = request.event;  // 'start' | 'media' | 'stop'

    // ── StreamStart ────────────────────────────────────────────────────────
    if (eventType === 'start') {
      const s = request.start;

      // Field names per Five9 developer guide.  Fallbacks handle variations.
      callId = s.vcc_call_id || s.call_id || callId || 'unknown';
      leg    = (s.call_leg   || s.callLeg || s.channel || 'unknown').toLowerCase();

      sessionKey = `${callId}:${leg}`;

      console.log(
        `[GR][${callId}][${leg}] StreamStart` +
        `  domain=${s.domain_id || s.domainId}` +
        `  agent=${s.agent_id || s.agentId}` +
        `  encoding=${s.encoding}  rate=${s.sample_per_second || s.sampleRate}`
      );

      const onTranscript = (t) => handleTranscript(t);
      ws = openElevenLabsSocket({ callId, leg, onTranscript });
      sessions.set(sessionKey, { ws, callId, leg });

      call.write({ call_id: callId, status: 'OK', message: 'Stream started' });
    }

    // ── StreamMedia ────────────────────────────────────────────────────────
    else if (eventType === 'media') {
      if (!ws) return;
      const m = request.media;
      sendAudioChunk(ws, m.payload);
    }

    // ── StreamStop ─────────────────────────────────────────────────────────
    else if (eventType === 'stop') {
      const id  = request.stop?.vcc_call_id || request.stop?.call_id || callId;
      const key = sessionKey || `${id}:${leg}`;
      console.log(`[GR][${id}][${leg}] StreamStop  reason=${request.stop?.reason}`);
      cleanupSession(key);
      call.end();
    }
  });

  call.on('end', () => {
    if (sessionKey) cleanupSession(sessionKey);
    call.end();
  });

  call.on('error', (err) => {
    console.error(`[GR][${callId}][${leg}] error:`, err.message);
    if (sessionKey) cleanupSession(sessionKey);
  });
}

function cleanupSession(key) {
  const s = sessions.get(key);
  if (!s) return;
  if (s.ws?.readyState === WebSocket.OPEN) s.ws.close();
  sessions.delete(key);
  console.log(`[GR][${s.callId}][${s.leg}] session cleaned up`);
}

// ─── Start gRPC server ────────────────────────────────────────────────────────

function buildServerCredentials() {
  if (GRPC_TLS === 'true') {
    if (!TLS_CERT_PATH || !TLS_KEY_PATH) throw new Error('GRPC_TLS=true but TLS_CERT_PATH/TLS_KEY_PATH not set');
    return grpc.ServerCredentials.createSsl(null, [{
      cert_chain:  fs.readFileSync(TLS_CERT_PATH),
      private_key: fs.readFileSync(TLS_KEY_PATH),
    }], false);
  }
  return grpc.ServerCredentials.createInsecure();
}

const grpcServer = new grpc.Server();
grpcServer.addService(proto.VoiceStreamService.service, { StartStream: startStream });

grpcServer.bindAsync(`0.0.0.0:${GRPC_PORT}`, buildServerCredentials(), (err, port) => {
  if (err) { console.error('gRPC bind error:', err); process.exit(1); }
  console.log(`gRPC  server listening on :${port} (TLS: ${GRPC_TLS})`);
});

// ─── HTTP server for Five9 webhook callbacks ──────────────────────────────────

const app = express();
app.use(express.json());

// ── Subscription validation (Five9 sends a GET before saving the subscription)
// Must respond with the SHA-256 hash of the trust token, as a JSON string.
app.get('/call-events', (_req, res) => {
  // Five9 expects: Content-Type: application/json, body: "<sha256hex>" (JSON-encoded string)
  res.json(TRUST_TOKEN_SHA256);
});

// ── CTI Call events — metadata: call start/end, transfers, agent, disposition
// Five9 authenticates these POSTs with X-F9-APIKEY header.
app.post('/call-events', (req, res) => {
  // Validate the API Key if configured (copy it from Five9 after subscription creation)
  if (FIVE9_API_KEY) {
    const incoming = req.headers['x-f9-apikey'];
    if (incoming !== FIVE9_API_KEY) {
      console.warn('[HTTP] CTI event rejected — bad/missing X-F9-APIKEY');
      return res.status(401).json({ error: 'Unauthorized' });
    }
  }
  console.log('[HTTP] CTI CallEvent:', JSON.stringify(req.body, null, 2));
  res.json({ received: true });
});

// ── Stream Status events — lifecycle of each gRPC stream leg (STREAMING / ENDED_NORMALLY / ERROR)
// URL format: POST /subscriptions/{subscriptionId}?event=StreamStatusNotification
// Fields: callId, domainId, callLeg, status, failureType, failureDetail, destinationUrl, occurredOn
app.post('/subscriptions/:subscriptionId', (req, res) => {
  const { subscriptionId } = req.params;
  const { callId, callLeg, status, failureType, failureDetail } = req.body;
  console.log(`[HTTP] StreamStatus [sub=${subscriptionId}] callId=${callId} leg=${callLeg} status=${status}` +
    (failureType ? ` failureType=${failureType} detail=${failureDetail}` : ''));
  res.json({ received: true });
});

app.get('/health', (_req, res) => {
  // Count unique calls (each call produces two sessions — agent + customer)
  const uniqueCalls = new Set([...sessions.values()].map(s => s.callId)).size;
  res.json({ status: 'ok', activeSessions: sessions.size, activeCallCount: uniqueCalls });
});

app.listen(Number(HTTP_PORT), () => {
  console.log(`HTTP  server listening on :${HTTP_PORT}`);
  console.log(`  Subscription validation → GET  http://HOST:${HTTP_PORT}/call-events`);
  console.log(`  CTI Events             → POST http://HOST:${HTTP_PORT}/call-events`);
  console.log(`  Stream Status          → POST http://HOST:${HTTP_PORT}/subscriptions/{subscriptionId}`);
});

process.on('SIGTERM', () => {
  for (const [key] of sessions) cleanupSession(key);
  grpcServer.forceShutdown();
  process.exit(0);
});
